version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test_frontend:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Linter
          command: npm run lint || echo "No lint script found"
      - run:
          name: Run Unit Tests
          command: npm test

  build_and_push_frontend:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Docker Buildx
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install all
            docker buildx create --use --name multi-platform-builder
      - run:
          name: Build and Push to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            
            VERSION="v0.0.${CIRCLE_BUILD_NUM}"
            IMAGE_NAME="zhaoxinmei/circleci-tasksphere-frontend"
            
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              -t $IMAGE_NAME:$VERSION \
              -t $IMAGE_NAME:latest \
              --push .

workflows:
  version: 2
  frontend_pipeline:
    jobs:
      - test_frontend
      
      - build_and_push_frontend:
          requires:
            - test_frontend
          filters:
            branches:
              only: main
